### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by tamasgal** [eisvogel-project/Eisvogel#54]
I am a little bit confused how to use this software. To give a bit of context: I was asked to install it on our clusters and now need to help a bit getting this software running with all the bells and whistles (including MPI). I understood from https://github.com/eisvogel-project/Eisvogel/issues/53 that Eisvogel is "header only".

I went to the `build/applications/dipole` folder (I guess that's a good start and then simply mimic the structure of the applications/examples) and compiled the `dipole` executable and unfortunately I got a `segmentation fault`

```
(base) ✔ ~/dev/Eisvogel/build/applications/dipole [main|✔]
14:37 $ ./dipole
Using MPI version 4.1, 1 processes
Segmentation fault (core dumped)
```

We use OpenMPI `4.1.3-oneapi2022.1.0` on our cluster.

Is there any documentation how to use or debug things?

Edit: btw. I titled this issue "Usage documentation" for now. I guess the segmentation fault is a user error, but probably more related to the missing docs ;)

**Comment by tamasgal** [comment]
I tried a few examples and one of them fails with another error:

```
(base) ✘-ABRT ~/dev/Eisvogel/build/examples/dipole_ice [main|✔]
15:41 $ ./dipole_ice testpath
Using MPI version 4.1, 1 processes
Constructed geom with start = [0, -400, 0] and end = [400, 200, 500]
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot create directory: No such file or directory [/scratch/midway3/windischhofer/eisvogel]
Aborted (core dumped)
```

This one is again different ;)

```
(base) ✘-ABRT ~/dev/Eisvogel/build/examples/plot_greens_function [main|✔]
15:41 $ ./export_greens_function  -h
terminate called without an active exception
Aborted (core dumped)
```

**Comment by philippwindischhofer** [comment]
Hi! I'm not surprised that they all crash, given that, right now, they require some combination of command-line arguments and changing hard-coded paths in the code. 

Making a long story short, the examples and example applications are not yet at the stage where they can be run out of the box, but are rather intended to show with example code how to use the rest of the library.

Specifically:

- `dipole` calculates the Green's function, given a refractive-index distribution and a signal chain impulse response (which you need to pass).
- `dipole_ice` calculates the Green's function for some fixed refractive-index distribution, but you need to adjust the path to the output directory (as you found).
- `exports_greens_function` requires an existing Green's function, for which it will export a low-granularity version in numpy-compatible binary format (so that it can then be processed or plotted in an almost arbitrary way).

**Comment by philippwindischhofer** [comment]
That said, if you wanted to improve the quality of the examples and add proper command-line parsing, a PR would be most welcome :-)

**Comment by philippwindischhofer** [comment]
Adding proper documentation is also on my list of things to do, but so far has been quite low-priority, unfortunately ...
